export const locales = ['en', 'zh-CN', 'ja', 'fr', 'ru', 'es', 'hi', 'pt', 'ms'] as const;
export type Locale = (typeof locales)[number];

export const localeMeta: Record<Locale, { label: string; native: string }> = {
  en: { label: 'English', native: 'English' }, 'zh-CN': { label: 'Chinese', native: '中文' },
  ja: { label: 'Japanese', native: '日本語' }, fr: { label: 'French', native: 'Français' },
  ru: { label: 'Russian', native: 'Русский' }, es: { label: 'Spanish', native: 'Español' },
  hi: { label: 'Hindi', native: 'हिन्दी' }, pt: { label: 'Portuguese', native: 'Português' }, ms: { label: 'Malay', native: 'Bahasa Melayu' },
};

export const copy: Record<Locale, Record<string, string>> = {
  en: { navCreate: 'Create', navWishes: 'Wish wall', navPricing: 'Plans', eyebrow: 'A small ritual for big feelings', title: 'Send a little wonder.', subtitle: 'Write a blessing. Make a wish. Let a meteor carry it somewhere bright.', create: 'Create a blessing', wish: 'Make a wish', moments: 'Choose a moment', birthday: 'Birthday', anniversary: 'Anniversary', holiday: 'Holiday', wedding: 'Wedding', close: 'Close', discover: 'Discover wishes', pricing: 'Plans' },
  'zh-CN': { navCreate: '创作', navWishes: '许愿墙', navPricing: '方案', eyebrow: '为重要心意留一点仪式感', title: '让心意化作流星。', subtitle: '写一段祝福，许一个愿望，让流星把它带往明亮的地方。', create: '生成祝福', wish: '许下愿望', moments: '选择场景', birthday: '生日', anniversary: '纪念日', holiday: '节日', wedding: '婚礼', close: '收起', discover: '看看大家的愿望', pricing: '方案' },
  ja: { navCreate: 'つくる', navWishes: '願いの広場', navPricing: 'プラン', eyebrow: '大切な気持ちに、小さな儀式を', title: '想いを流星に。', subtitle: '祝福を書いて、願いをかけて。流星が明るい場所へ運びます。', create: '祝福をつくる', wish: '願いをかける', moments: 'シーンを選ぶ', birthday: '誕生日', anniversary: '記念日', holiday: '祝日', wedding: '結婚式', close: '閉じる', discover: 'みんなの願いを見る', pricing: 'プラン' },
  fr: { navCreate: 'Créer', navWishes: 'Mur de vœux', navPricing: 'Offres', eyebrow: 'Un petit rituel pour les grands élans', title: 'Envoyez un peu de merveille.', subtitle: 'Écrivez un message, faites un vœu, laissez une météore l’emporter.', create: 'Créer un message', wish: 'Faire un vœu', moments: 'Choisir un moment', birthday: 'Anniversaire', anniversary: 'Commémoration', holiday: 'Fête', wedding: 'Mariage', close: 'Fermer', discover: 'Découvrir les vœux', pricing: 'Offres' },
  ru: { navCreate: 'Создать', navWishes: 'Стена желаний', navPricing: 'Тарифы', eyebrow: 'Маленький ритуал для больших чувств', title: 'Отправьте немного чуда.', subtitle: 'Напишите пожелание, загадайте мечту — пусть метеор унесёт её к свету.', create: 'Создать пожелание', wish: 'Загадать желание', moments: 'Выберите повод', birthday: 'День рождения', anniversary: 'Годовщина', holiday: 'Праздник', wedding: 'Свадьба', close: 'Закрыть', discover: 'Открыть желания', pricing: 'Тарифы' },
  es: { navCreate: 'Crear', navWishes: 'Muro de deseos', navPricing: 'Planes', eyebrow: 'Un pequeño ritual para grandes sentimientos', title: 'Envía un poco de asombro.', subtitle: 'Escribe una bendición, pide un deseo y deja que un meteoro lo lleve.', create: 'Crear una bendición', wish: 'Pedir un deseo', moments: 'Elige un momento', birthday: 'Cumpleaños', anniversary: 'Aniversario', holiday: 'Fiesta', wedding: 'Boda', close: 'Cerrar', discover: 'Descubrir deseos', pricing: 'Planes' },
  hi: { navCreate: 'बनाएँ', navWishes: 'इच्छा दीवार', navPricing: 'प्लान', eyebrow: 'बड़े एहसासों के लिए एक छोटा अनुष्ठान', title: 'थोड़ा जादू भेजिए।', subtitle: 'आशीर्वाद लिखें, इच्छा करें और उसे उल्का के साथ रोशनी तक पहुँचने दें।', create: 'आशीर्वाद बनाएँ', wish: 'इच्छा करें', moments: 'अवसर चुनें', birthday: 'जन्मदिन', anniversary: 'वर्षगांठ', holiday: 'त्योहार', wedding: 'शादी', close: 'बंद करें', discover: 'इच्छाएँ देखें', pricing: 'प्लान' },
  pt: { navCreate: 'Criar', navWishes: 'Mural de desejos', navPricing: 'Planos', eyebrow: 'Um pequeno ritual para grandes sentimentos', title: 'Envie um pouco de encanto.', subtitle: 'Escreva uma bênção, faça um desejo e deixe um meteoro levá-lo à luz.', create: 'Criar uma bênção', wish: 'Fazer um desejo', moments: 'Escolha um momento', birthday: 'Aniversário', anniversary: 'Data especial', holiday: 'Feriado', wedding: 'Casamento', close: 'Fechar', discover: 'Descobrir desejos', pricing: 'Planos' },
  ms: { navCreate: 'Cipta', navWishes: 'Dinding hajat', navPricing: 'Pelan', eyebrow: 'Ritual kecil untuk perasaan yang besar', title: 'Kirim sedikit keajaiban.', subtitle: 'Tulis ucapan, buat hajat, dan biarkan meteor membawanya ke cahaya.', create: 'Cipta ucapan', wish: 'Buat hajat', moments: 'Pilih momen', birthday: 'Hari jadi', anniversary: 'Ulang tahun', holiday: 'Perayaan', wedding: 'Perkahwinan', close: 'Tutup', discover: 'Teroka hajat', pricing: 'Pelan' },
};

export function isLocale(value: string | undefined): value is Locale { return !!value && locales.includes(value as Locale); }
export function detectLocale(header: string | null): Locale { const raw = header?.toLowerCase() ?? ''; return locales.find((locale) => raw.startsWith(locale.toLowerCase().split('-')[0])) ?? 'en'; }
